'''
This file was used to figure out why various OpenML datasets failed to produce usable results for the sampling
benchmark. See inline comments below for various error messages encountered and what they mean.
'''
from data.io import read_dataset
from data.repo import download_dataset
from data.config import Preprocess

ids = [
    373,   40593, 41228, 41469, 41479, 41542, 41554, 41701, 41714, 41724, 41734, 41744, 41754, 41764, 41774, 41784,
    41794, 41804, 41814, 41824, 41834, 41844, 41854, 41864, 41874, 41884, 41894, 4535, 1414,  374,   40594, 4138,
    41470, 41485, 41545, 41556, 41702, 41715, 41725, 41735, 41745, 41755, 41765, 41775, 41785, 41795, 41805, 41815,
    41825, 41835, 41845, 41855, 41865, 41875, 41885, 41895, 4540, 1419,  376,   40595, 4139,  41471, 41486, 41546,
    41557, 41703, 41716, 41726, 41736, 41746, 41756, 41766, 41776, 41786, 41796, 41806, 41816, 41826, 41836, 41846,
    41856, 41866, 41876, 41886, 41896, 4548, 1420,  379,   40596, 4140,  41472, 41488, 41547, 41558, 41707, 41717,
    41727, 41737, 41747, 41757, 41767, 41777, 41787, 41797, 41807, 41817, 41827, 41837, 41847, 41857, 41867, 41877,
    41887, 41897, 4551, 23383, 380,   40597, 41463, 41473, 41489, 41548, 41559, 41708, 41718, 41728, 41738, 41748,
    41758, 41768, 41778, 41788, 41798, 41808, 41818, 41828, 41838, 41848, 41858, 41868, 41878, 41888, 41898, 4553,
    23394, 40588, 40869, 41464, 41474, 41490, 41549, 41567, 41709, 41719, 41729, 41739, 41749, 41759, 41769, 41779,
    41789, 41799, 41809, 41819, 41829, 41839, 41849, 41859, 41869, 41879, 41889, 41919, 493, 23396, 40589, 40976,
    41465, 41475, 41491, 41550, 41582, 41710, 41720, 41730, 41740, 41750, 41760, 41770, 41780, 41790, 41800, 41810,
    41820, 41830, 41840, 41850, 41860, 41870, 41880, 41890, 41939, 501, 23420, 40590, 40992, 41466, 41476, 41492,
    41551, 41668, 41711, 41721, 41731, 41741, 41751, 41761, 41771, 41781, 41791, 41801, 41811, 41821, 41831, 41841,
    41851, 41861, 41871, 41881, 41891, 4353,  680, 274,   40591, 40993, 41467, 41477, 41496, 41552, 41669, 41712,
    41722, 41732, 41742, 41752, 41762, 41772, 41782, 41792, 41802, 41812, 41822, 41832, 41842, 41852, 41862, 41872,
    41882, 41892, 4531,  705, 40592, 41039, 41468, 41478, 41510, 41553, 41700, 41713, 41723, 41733, 41743, 41753,
    41763, 41773, 41783, 41793, 41803, 41813, 41823, 41833, 41843, 41853, 41863, 41873, 41883, 41893, 4533]

# Error message: dataset.dataset.default_target_attribute is None
# y is essentially just an empty (size 0) array which means we have nothing to regress or classify on for our models.
none_target_ids = [
    1184, 41542, 4535, 4138, 4540, 1419, 4139, 4548, 1420, 4140, 4551, 23383, 4553, 23394, 40869, 493, 23396, 40976,
    501, 23420, 40992, 41668, 4353, 680, 40993, 41669, 4531, 705, 41039, 4533]

# Error message: PyOpenMLError('Dataset 41862 not compatible, PyOpenML cannot handle string features',)
# Doesn't look like we can do anything about these errors. It seems to stem from a python-openml version 0.8 library
# issue. Perhaps it has been resolved in python-openml 0.9?
string_features_ids = [
    41228, 274, 373, 374, 376, 379, 380, 1414, 41823, 41463, 41496, 41700, 41701, 41702, 41703, 41707, 41708, 41709,
    41710, 41711, 41712, 41713, 41714, 41715, 41716, 41717, 41718, 41719, 41720, 41721, 41722, 41723, 41724, 41725,
    41726, 41727, 41728, 41729, 41730, 41731, 41732, 41733, 41734, 41735, 41736, 41737, 41738, 41739, 41740, 41741,
    41742, 41743, 41744, 41745, 41746, 41747, 41748, 41749, 41750, 41751, 41752, 41753, 41754, 41755, 41756, 41757,
    41758, 41759, 41760, 41761, 41762, 41763, 41764, 41765, 41766, 41767, 41768, 41769, 41770, 41771, 41772, 41773,
    41774, 41775, 41776, 41777, 41778, 41779, 41780, 41781, 41782, 41783, 41784, 41785, 41786, 41787, 41788, 41789,
    41790, 41791, 41792, 41793, 41794, 41795, 41796, 41797, 41798, 41799, 41800, 41801, 41802, 41803, 41804, 41805,
    41806, 41807, 41808, 41809, 41810, 41811, 41812, 41813, 41814, 41815, 41816, 41817, 41818, 41819, 41820, 41821,
    41822, 41824, 41825, 41826, 41827, 41828, 41829, 41832, 41833, 41830, 41831, 41834, 41835, 41836, 41837, 41838,
    41839, 41840, 41841, 41842, 41843, 41844, 41845, 41846, 41849, 41850, 41851, 41852, 41853, 41847, 41848, 41854,
    41855, 41856, 41857, 41858, 41859, 41862, 41863, 41860, 41861, 41864, 41865, 41866, 41867, 41868, 41869, 41872,
    41873, 41870, 41871, 41874, 41875, 41876, 41877, 41878, 41879, 41880, 41881, 41882, 41883, 41884, 41885, 41886,
    41887, 41888, 41889, 41890, 41891, 41892, 41894, 41895, 41896, 41897, 41898, 41893, 41919, 41939]

# Error message: NotImplementedError('Number of requested targets 22 is not implemented.',)
# Doesn't look like we can do anything about these errors. It seems to stem from a python-openml version 0.8 library
# issue. Perhaps it has been resolved in python-openml 0.9?
multiple_target_ids = [
    41472, 41473, 41474, 41475, 41476, 41477, 41478, 41479, 40588, 41485, 41486, 40589, 41488, 41489, 41490, 41491,
    41492, 40590, 40591, 40592, 40593, 40594, 40595, 40596, 40597, 41510, 41545, 41546, 41547, 41548, 41549, 41550,
    41551, 41552, 41553, 41554, 41556, 41557, 41558, 41559, 41567, 41582, 41464, 41465, 41466, 41467, 41468, 41469,
    41470, 41471]

remaining_ids = set(ids) - set(none_target_ids) - set(string_features_ids) - set(multiple_target_ids)

print(f'{len(remaining_ids)} ids left -', ', '.join(str(_) for _ in list(ids)[:5]) + '...')
for dataset_id in remaining_ids:
    try:
        d = download_dataset(dataset_id)
    except Exception as e:
        print(dataset_id, repr(e))
    else:
        print('Unexpected outcome', dataset_id)
